PROGRAM FOR TOWER OF HANIO WITH 3 PEGS :A,B & C AND 10 DISKS. 
ctr=[0]#counter
def tower(n,frm,to,aux,ctr):
    if n==0:
        return
    tower(n-1,frm,aux,to,ctr)
    print(f"move {n} from {frm} to {to}")
    ctr[0]+=1
    tower(n-1,aux,to,frm,ctr)
n=10
tower(n,'a','c','b',ctr)
print(ctr)

OUTPUT:
move 1 from c to a
move 5 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 6 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 4 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 5 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 4 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 7 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 5 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 4 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 6 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 4 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 5 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 8 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 4 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 5 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 4 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 6 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 5 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 4 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 7 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 4 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 5 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 6 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 4 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 5 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 4 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 9 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 5 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 4 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 6 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 4 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 5 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 7 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 4 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 5 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 4 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 6 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 5 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 4 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 8 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 4 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 5 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 6 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 4 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 5 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 4 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 7 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 5 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 4 from c to b
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 6 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 4 from b to a
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 3 from c to a
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 5 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
move 3 from a to b
move 1 from c to a
move 2 from c to b
move 1 from a to b
move 4 from a to c
move 1 from b to c
move 2 from b to a
move 1 from c to a
move 3 from b to c
move 1 from a to b
move 2 from a to c
move 1 from b to c
[1023]
